import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

type Logger = {
  info?: (msg: string) => void;
  warn?: (msg: string) => void;
  debug?: (msg: string) => void;
};

type PluginApi = {
  on?: (hookName: string, handler: (event: any, ctx: any) => any, options?: { priority?: number }) => void;
  registerService?: (service: {
    id: string;
    start: () => Promise<void> | void;
    stop?: () => Promise<void> | void;
  }) => void;
  config?: any;
  pluginConfig?: PluginConfig;
  logger?: Logger;
};

export type PluginConfig = {
  enabled?: boolean;
  codexHome?: string;
  promptFile?: string;
  instructionsCacheFile?: string;
  startupDeveloperInstructions?: string;
  startupDeveloperInstructionsFile?: string;
  hookPriority?: number;
  debugHook?: boolean;
};

export type ReconcileResult = {
  text: string;
  changed: boolean;
};

export type ObservedInstructions = {
  hookName: "before_prompt_build";
  developerInstructions: string;
};

type HookDebugLogger = (message: string) => void;

const DEFAULT_PROMPT_FILE = "openclaw-app-server-instructions.md";
const DEFAULT_INSTRUCTIONS_CACHE_FILE = ".openclaw-app-server-developer-instructions.md";
const DEFAULT_STARTUP_DEVELOPER_INSTRUCTIONS_FILE = "openclaw-developer-instructions.md";
const DEFAULT_PRIORITY = 10000;
const OPENCLAW_WORKSPACE_INSTRUCTIONS_HEADER = "## OpenClaw Workspace Instructions";
const DEFAULT_CODEX_OPENCLAW_DEVELOPER_INSTRUCTIONS =
  "You are a personal agent running inside OpenClaw. OpenClaw has dynamic tools for OpenClaw-owned messaging, cron, sessions, media, gateway, and nodes.\n\nUse Codex native `spawn_agent` for Codex subagents. Use OpenClaw `sessions_spawn` only for OpenClaw or ACP delegation.";
const SPECIAL_TURN_INSTRUCTION_MARKERS = [
  "This is an OpenClaw cron automation turn.",
  "This is an OpenClaw heartbeat turn.",
  "## OpenClaw Heartbeat Workspace",
];
const GENERATED_PROMPT_PREFIX_LINES = [
  "# OpenClaw Developer Instructions",
  "",
  "This file is generated by the system-prompt plugin.",
  "Use the following OpenClaw developer instructions as the Codex app-server model instructions.",
];
const GENERATED_PROMPT_PREFIX = [...GENERATED_PROMPT_PREFIX_LINES, "", ""].join("\n");
const GENERATED_PROMPT_PREFIX_COMPAT = [...GENERATED_PROMPT_PREFIX_LINES, ""].join("\n");

function expandHome(value: string): string {
  if (value === "~") return os.homedir();
  if (value.startsWith("~/")) return path.join(os.homedir(), value.slice(2));
  return value;
}

function isAbsolutePath(value: string): boolean {
  return path.isAbsolute(value) || /^[A-Za-z]:[\\/]/.test(value);
}

function resolveOpenClawStateDir(env: NodeJS.ProcessEnv): string {
  return path.resolve(expandHome(String(env.OPENCLAW_STATE_DIR ?? env.OPENCLAW_HOME ?? "~/.openclaw")));
}

function resolveDefaultOpenClawAgentDir(env: NodeJS.ProcessEnv): string {
  const configured = String(env.OPENCLAW_AGENT_DIR ?? "").trim();
  if (configured) return path.resolve(expandHome(configured));
  return path.join(resolveOpenClawStateDir(env), "agents", "main", "agent");
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

export function normalizeDeveloperInstructions(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

export function splitOpenClawDeveloperInstructions(openClawDeveloperInstructions: string): {
  baseInstructions: string;
  workspaceInstructions: string;
  split: boolean;
} {
  const normalized = normalizeDeveloperInstructions(openClawDeveloperInstructions);
  if (!normalized) {
    throw new Error("OpenClaw developer instructions are empty");
  }

  const markerIndex = normalized.indexOf(OPENCLAW_WORKSPACE_INSTRUCTIONS_HEADER);
  if (markerIndex === -1) {
    return {
      baseInstructions: normalized,
      workspaceInstructions: normalized,
      split: false,
    };
  }

  const baseInstructions = normalizeDeveloperInstructions(normalized.slice(0, markerIndex));
  const workspaceInstructions = normalizeDeveloperInstructions(normalized.slice(markerIndex));
  if (!baseInstructions || !workspaceInstructions) {
    return {
      baseInstructions: normalized,
      workspaceInstructions: normalized,
      split: false,
    };
  }

  return {
    baseInstructions,
    workspaceInstructions,
    split: true,
  };
}

export function renderCustomSystemPrompt(openClawDeveloperInstructions: string): string {
  return splitOpenClawDeveloperInstructions(openClawDeveloperInstructions).workspaceInstructions;
}

export function renderCodexBaseInstructions(openClawDeveloperInstructions: string): string {
  return splitOpenClawDeveloperInstructions(openClawDeveloperInstructions).baseInstructions;
}

export function reconcileCodexConfigToml(existingToml: string, promptFilePath: string): ReconcileResult {
  const normalizedPath = path.resolve(expandHome(promptFilePath));
  const desiredLine = `model_instructions_file = ${tomlString(normalizedPath)}`;
  const linePattern = /^(\s*)model_instructions_file\s*=\s*(?:"(?:\\.|[^"\\])*"|'[^']*'|[^\s#]+)(\s*(?:#.*)?)?$/;
  const tablePattern = /^\s*\[[^\]]+\]\s*(?:#.*)?$/;
  const lines = existingToml.split(/\r?\n/);

  let changed = false;
  let replaced = false;
  let inRootTable = true;
  const nextLines = lines.flatMap((line) => {
    if (tablePattern.test(line)) {
      inRootTable = false;
    }

    const match = line.match(linePattern);
    if (!match) return [line];
    if (!inRootTable || replaced) {
      changed = true;
      return [];
    }

    replaced = true;
    const nextLine = `${match[1]}${desiredLine}${match[2] ?? ""}`;
    if (nextLine !== line) changed = true;
    return [nextLine];
  });

  if (!replaced) {
    const firstTableIndex = nextLines.findIndex((line) => tablePattern.test(line));
    const insertIndex = firstTableIndex === -1 ? nextLines.length : firstTableIndex;
    const insertion = ["# Managed by the system-prompt OpenClaw plugin.", desiredLine];
    if (insertIndex > 0 && nextLines[insertIndex - 1] !== "") {
      insertion.unshift("");
    }
    if (insertIndex < nextLines.length && nextLines[insertIndex] !== "") {
      insertion.push("");
    }
    nextLines.splice(insertIndex, 0, ...insertion);
    changed = true;
  }

  const text = nextLines.join("\n");
  return { text: text.endsWith("\n") ? text : `${text}\n`, changed };
}

export function resolveCodexHome(config: PluginConfig = {}, env: NodeJS.ProcessEnv = process.env): string {
  const configured = String(config.codexHome ?? env.CODEX_HOME ?? "").trim();
  if (configured) return path.resolve(expandHome(configured));

  return path.join(resolveDefaultOpenClawAgentDir(env), "codex-home");
}

export function resolvePromptFilePath(codexHome: string, config: PluginConfig = {}): string {
  const configured = String(config.promptFile ?? DEFAULT_PROMPT_FILE).trim() || DEFAULT_PROMPT_FILE;
  const expanded = expandHome(configured);
  return path.resolve(isAbsolutePath(expanded) ? expanded : path.join(codexHome, expanded));
}

export function resolveInstructionsCacheFilePath(codexHome: string, config: PluginConfig = {}): string {
  const configured =
    String(config.instructionsCacheFile ?? DEFAULT_INSTRUCTIONS_CACHE_FILE).trim() ||
    DEFAULT_INSTRUCTIONS_CACHE_FILE;
  const expanded = expandHome(configured);
  return path.resolve(isAbsolutePath(expanded) ? expanded : path.join(codexHome, expanded));
}

export function extractDeveloperInstructionsFromGeneratedPrompt(value: unknown): string | null {
  const normalized = normalizeDeveloperInstructions(value);
  if (!normalized) {
    return null;
  }

  if (normalized.startsWith(GENERATED_PROMPT_PREFIX)) {
    return normalizeDeveloperInstructions(normalized.slice(GENERATED_PROMPT_PREFIX.length));
  }

  if (normalized.startsWith(GENERATED_PROMPT_PREFIX_COMPAT)) {
    return normalizeDeveloperInstructions(
      normalized.slice(GENERATED_PROMPT_PREFIX_COMPAT.length),
    );
  }

  return normalized;
}

export function isStandardOpenClawDeveloperInstructions(value: unknown): boolean {
  const normalized = normalizeDeveloperInstructions(value);
  if (!normalized) return false;
  if (!normalized.includes(DEFAULT_CODEX_OPENCLAW_DEVELOPER_INSTRUCTIONS.split("\n\n")[0])) return false;
  if (!normalized.includes(OPENCLAW_WORKSPACE_INSTRUCTIONS_HEADER)) return false;
  return !SPECIAL_TURN_INSTRUCTION_MARKERS.some((marker) => normalized.includes(marker));
}

function describePromptBuildDecision(value: unknown): {
  normalized: string | null;
  hasStandardCore: boolean;
  markerIndex: number;
  specialMarker: string | null;
  standard: boolean;
  reason: string | null;
} {
  const normalized = normalizeDeveloperInstructions(value);
  const standardCore = DEFAULT_CODEX_OPENCLAW_DEVELOPER_INSTRUCTIONS.split("\n\n")[0];
  const hasStandardCore = normalized ? normalized.includes(standardCore) : false;
  const markerIndex = normalized ? normalized.indexOf(OPENCLAW_WORKSPACE_INSTRUCTIONS_HEADER) : -1;
  const specialMarker = normalized
    ? SPECIAL_TURN_INSTRUCTION_MARKERS.find((marker) => normalized.includes(marker)) ?? null
    : null;

  if (!normalized) {
    return {
      normalized,
      hasStandardCore,
      markerIndex,
      specialMarker,
      standard: false,
      reason: "empty",
    };
  }
  if (!hasStandardCore) {
    return {
      normalized,
      hasStandardCore,
      markerIndex,
      specialMarker,
      standard: false,
      reason: "missing-standard-core",
    };
  }
  if (markerIndex === -1) {
    return {
      normalized,
      hasStandardCore,
      markerIndex,
      specialMarker,
      standard: false,
      reason: "missing-workspace-marker",
    };
  }
  if (specialMarker) {
    return {
      normalized,
      hasStandardCore,
      markerIndex,
      specialMarker,
      standard: false,
      reason: "special-turn-marker",
    };
  }

  return {
    normalized,
    hasStandardCore,
    markerIndex,
    specialMarker,
    standard: true,
    reason: null,
  };
}

export function extractDeveloperInstructions(
  hookName: ObservedInstructions["hookName"],
  event: any,
  _ctx: any,
): ObservedInstructions | null {
  const normalized = normalizeDeveloperInstructions(
    event?.systemPrompt ?? event?.developerInstructions,
  );
  return normalized ? { hookName, developerInstructions: normalized } : null;
}

export function createPromptBuildHookBehavior(opts: {
  observe?: (observed: ObservedInstructions) => Promise<void> | void;
  debug?: HookDebugLogger;
}) {
  return async (event: any, ctx: any) => {
    const rawValue = event?.systemPrompt ?? event?.developerInstructions;
    const decision = describePromptBuildDecision(rawValue);
    const eventKeys = event && typeof event === "object"
      ? Object.keys(event).slice(0, 12).join(",")
      : "";
    opts.debug?.(
      `[system-prompt] before_prompt_build input keys=${eventKeys || "none"} hasSystemPrompt=${typeof event?.systemPrompt === "string"} hasDeveloperInstructions=${typeof event?.developerInstructions === "string"} hasPrompt=${typeof event?.prompt === "string"} chars=${decision.normalized?.length ?? 0} markerIndex=${decision.markerIndex} hasStandardCore=${decision.hasStandardCore} specialMarker=${decision.specialMarker ?? "none"}`,
    );

    const observed = extractDeveloperInstructions("before_prompt_build", event, ctx);
    if (!observed) {
      opts.debug?.("[system-prompt] before_prompt_build return=undefined reason=empty");
      return undefined;
    }
    if (!decision.standard) {
      opts.debug?.(
        `[system-prompt] before_prompt_build return=undefined reason=${decision.reason ?? "not-standard"}`,
      );
      return undefined;
    }

    await opts.observe?.(observed);
    const replacement = renderCustomSystemPrompt(observed.developerInstructions);
    opts.debug?.(
      `[system-prompt] before_prompt_build return=systemPrompt chars=${replacement.length}`,
    );

    return {
      systemPrompt: replacement,
    };
  };
}

async function writeFileIfChanged(filePath: string, contents: string): Promise<boolean> {
  try {
    const current = await fs.readFile(filePath, "utf8");
    if (current === contents) return false;
  } catch (error: any) {
    if (error?.code !== "ENOENT") throw error;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, "utf8");
  return true;
}

export async function generatePromptAndReconcileConfig(opts: {
  codexHome: string;
  promptFilePath: string;
  developerInstructions: string;
  instructionsCacheFilePath?: string;
}): Promise<{ promptChanged: boolean; configChanged: boolean; cacheChanged: boolean; configPath: string }> {
  if (!normalizeDeveloperInstructions(opts.developerInstructions)) {
    throw new Error("OpenClaw developer instructions are empty");
  }

  const developerInstructions = opts.developerInstructions;
  const promptChanged = await writeFileIfChanged(opts.promptFilePath, developerInstructions);
  const cacheChanged = opts.instructionsCacheFilePath
    ? await writeFileIfChanged(
        opts.instructionsCacheFilePath,
        developerInstructions.endsWith("\n") ? developerInstructions : `${developerInstructions}\n`,
      )
    : false;

  const configPath = path.join(opts.codexHome, "config.toml");
  let existing = "";
  try {
    existing = await fs.readFile(configPath, "utf8");
  } catch (error: any) {
    if (error?.code !== "ENOENT") throw error;
  }

  const reconciled = reconcileCodexConfigToml(existing, opts.promptFilePath);
  let configChanged = false;
  if (reconciled.changed || existing !== reconciled.text) {
    await fs.mkdir(path.dirname(configPath), { recursive: true });
    await fs.writeFile(configPath, reconciled.text, "utf8");
    configChanged = true;
  }

  return { promptChanged, configChanged, cacheChanged, configPath };
}

export async function reconcileCodexConfigFile(opts: {
  codexHome: string;
  promptFilePath: string;
}): Promise<{ configChanged: boolean; configPath: string }> {
  const configPath = path.join(opts.codexHome, "config.toml");
  let existing = "";
  try {
    existing = await fs.readFile(configPath, "utf8");
  } catch (error: any) {
    if (error?.code !== "ENOENT") throw error;
  }

  const reconciled = reconcileCodexConfigToml(existing, opts.promptFilePath);
  if (reconciled.changed || existing !== reconciled.text) {
    await fs.mkdir(path.dirname(configPath), { recursive: true });
    await fs.writeFile(configPath, reconciled.text, "utf8");
    return { configChanged: true, configPath };
  }

  return { configChanged: false, configPath };
}

async function readOptionalText(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error: any) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

export function resolveBundledStartupDeveloperInstructionsFile(): string {
  return path.join(path.dirname(fileURLToPath(import.meta.url)), DEFAULT_STARTUP_DEVELOPER_INSTRUCTIONS_FILE);
}

export async function resolveStartupDeveloperInstructions(opts: {
  config?: PluginConfig;
  defaultStartupDeveloperInstructionsFile?: string;
}): Promise<{ developerInstructions: string; source: string } | null> {
  const direct = normalizeDeveloperInstructions(opts.config?.startupDeveloperInstructions);
  if (direct) {
    return {
      developerInstructions: String(opts.config?.startupDeveloperInstructions),
      source: "config.startupDeveloperInstructions",
    };
  }

  const configuredSource =
    normalizeDeveloperInstructions(opts.config?.startupDeveloperInstructionsFile) ??
    opts.defaultStartupDeveloperInstructionsFile ??
    resolveBundledStartupDeveloperInstructionsFile();
  const sourcePath = path.resolve(expandHome(configuredSource));
  const text = await readOptionalText(sourcePath);
  if (normalizeDeveloperInstructions(text)) {
    return { developerInstructions: text ?? "", source: sourcePath };
  }

  return null;
}

function getPluginConfig(api: PluginApi): PluginConfig {
  const rootConfig = typeof api.config?.get === "function" ? api.config.get() : api.config;
  return (api.pluginConfig ?? rootConfig?.plugins?.entries?.["system-prompt"]?.config ?? {}) as PluginConfig;
}

function onWithPriority(
  api: PluginApi,
  hookName: string,
  handler: (event: any, ctx: any) => any,
  priority: number,
): "options" | "plain" {
  if (typeof api.on !== "function") {
    throw new Error("OpenClaw plugin API does not expose api.on");
  }

  try {
    api.on(hookName, handler, { priority });
    return "options";
  } catch {
    api.on(hookName, handler);
    return "plain";
  }
}

export default function register(api: PluginApi) {
  const cfg = getPluginConfig(api);
  if (cfg.enabled === false) return;

  const rootConfig = typeof api.config?.get === "function" ? api.config.get() : api.config;
  const codexHome = resolveCodexHome({ ...rootConfig, ...cfg });
  const promptFilePath = resolvePromptFilePath(codexHome, cfg);
  const instructionsCacheFilePath = resolveInstructionsCacheFilePath(codexHome, cfg);
  const priority = Number.isFinite(cfg.hookPriority) ? Number(cfg.hookPriority) : DEFAULT_PRIORITY;

  let lastObserved = "";
  const generateFromInstructions = async (developerInstructions: string) => {
    const normalized = normalizeDeveloperInstructions(developerInstructions);
    if (!normalized) return null;
    if (normalized === lastObserved) {
      const configResult = await reconcileCodexConfigFile({ codexHome, promptFilePath });
      return {
        promptChanged: false,
        configChanged: configResult.configChanged,
        cacheChanged: false,
        configPath: configResult.configPath,
      };
    }
    lastObserved = normalized;

    return await generatePromptAndReconcileConfig({
      codexHome,
      promptFilePath,
      instructionsCacheFilePath,
      developerInstructions: normalized,
    });
  };

  const start = async () => {
    const startup = await resolveStartupDeveloperInstructions({
      config: cfg,
    });

    if (!startup) {
      const configResult = await reconcileCodexConfigFile({ codexHome, promptFilePath });
      api.logger?.warn?.(
        `[system-prompt] startup has no canonical developer instructions source; reconciled config=${configResult.configChanged} but did not regenerate ${promptFilePath}`,
      );
      return;
    }

    const result = await generateFromInstructions(startup.developerInstructions);
    if (!result) return;

    api.logger?.info?.(
      `[system-prompt] startup generated prompt from ${startup.source}; prompt=${promptFilePath} promptChanged=${result.promptChanged} configChanged=${result.configChanged} cacheChanged=${result.cacheChanged}`,
    );
  };

  if (typeof api.registerService === "function") {
    api.registerService({
      id: "system-prompt",
      start,
    });
  } else {
    void start().catch((error: unknown) => {
      api.logger?.warn?.(
        `[system-prompt] startup prompt generation failed: ${String(error)}`,
      );
    });
  }

  const promptBuildMode = onWithPriority(
    api,
    "before_prompt_build",
    createPromptBuildHookBehavior({
      debug: cfg.debugHook ? (message) => api.logger?.info?.(message) : undefined,
    }),
    priority,
  );

  api.logger?.info?.(
    `[system-prompt] loaded with before_prompt_build hook (${promptBuildMode}); systemPrompt replacement active`,
  );
}
