import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import register, {
  createPromptBuildHookBehavior,
  extractDeveloperInstructionsFromGeneratedPrompt,
  extractDeveloperInstructions,
  generatePromptAndReconcileConfig,
  isStandardOpenClawDeveloperInstructions,
  reconcileCodexConfigToml,
  renderCodexBaseInstructions,
  renderCustomSystemPrompt,
  resolveBundledStartupDeveloperInstructionsFile,
  resolveCodexHome,
  resolveInstructionsCacheFilePath,
  resolvePromptFilePath,
  resolveStartupDeveloperInstructions,
  splitOpenClawDeveloperInstructions,
} from "./index.js";

const STANDARD_CORE =
  "You are a personal agent running inside OpenClaw. OpenClaw has dynamic tools for OpenClaw-owned messaging, cron, sessions, media, gateway, and nodes.\n\nUse Codex native `spawn_agent` for Codex subagents. Use OpenClaw `sessions_spawn` only for OpenClaw or ACP delegation.";

const LEGACY_GENERATED_PROMPT = [
  "# OpenClaw Developer Instructions",
  "",
  "This file is generated by the system-prompt plugin.",
  "Use the following OpenClaw developer instructions as the Codex app-server model instructions.",
  "",
  "",
  "Cached prompt",
  "",
].join("\n");

test("splits OpenClaw developer instructions at workspace header", () => {
  const split = splitOpenClawDeveloperInstructions(
    [
      "Top section.",
      "",
      "## OpenClaw Workspace Instructions",
      "",
      "Bottom section.",
    ].join("\n"),
  );

  assert.deepEqual(split, {
    baseInstructions: "Top section.",
    workspaceInstructions: "## OpenClaw Workspace Instructions\n\nBottom section.",
    split: true,
  });
});

test("preserves previous behavior when workspace header is absent", () => {
  const split = splitOpenClawDeveloperInstructions("Do the thing.\nKeep it scoped.");

  assert.deepEqual(split, {
    baseInstructions: "Do the thing.\nKeep it scoped.",
    workspaceInstructions: "Do the thing.\nKeep it scoped.",
    split: false,
  });
});

test("renders prompt-build replacement as workspace-tail contents", () => {
  const prompt = renderCustomSystemPrompt(
    [
      "Top section.",
      "",
      "## OpenClaw Workspace Instructions",
      "",
      "Bottom section.",
    ].join("\n"),
  );

  assert.equal(prompt, "## OpenClaw Workspace Instructions\n\nBottom section.");
});

test("renders Codex base instructions as pre-workspace contents", () => {
  const prompt = renderCodexBaseInstructions(
    [
      "Top section.",
      "",
      "## OpenClaw Workspace Instructions",
      "",
      "Bottom section.",
    ].join("\n"),
  );

  assert.equal(prompt, "Top section.");
});

test("renders unsplit OpenClaw developer instructions as raw Codex prompt contents", () => {
  const prompt = renderCustomSystemPrompt("Do the thing.\nKeep it scoped.");

  assert.equal(prompt, "Do the thing.\nKeep it scoped.");
  assert.equal(prompt.includes("generated by the system-prompt plugin"), false);
});

test("reconciles an existing model_instructions_file entry", () => {
  const result = reconcileCodexConfigToml(
    [
      'model = "gpt-5-codex"',
      'model_instructions_file = "/old/path.md" # keep comment',
      "",
    ].join("\n"),
    "/tmp/new prompt.md",
  );

  assert.equal(result.changed, true);
  assert.match(result.text, /model = "gpt-5-codex"/);
  assert.match(result.text, /model_instructions_file = "\/tmp\/new prompt\.md" # keep comment/);
});

test("appends model_instructions_file when missing", () => {
  const result = reconcileCodexConfigToml('model = "gpt-5-codex"\n', "/tmp/generated.md");

  assert.equal(result.changed, true);
  assert.match(result.text, /Managed by the system-prompt/);
  assert.match(result.text, /model_instructions_file = "\/tmp\/generated\.md"/);
  assert.equal(result.text.endsWith("\n"), true);
});

test("places model_instructions_file at TOML root before project tables", () => {
  const result = reconcileCodexConfigToml(
    [
      '[projects."/repo"]',
      'trust_level = "trusted"',
      "",
      "# Managed by the system-prompt OpenClaw plugin.",
      'model_instructions_file = "/nested/path.md"',
      "",
    ].join("\n"),
    "/tmp/generated.md",
  );

  assert.equal(result.changed, true);
  assert.match(
    result.text,
    /^# Managed by the system-prompt OpenClaw plugin\.\nmodel_instructions_file = "\/tmp\/generated\.md"\n\n\[projects\."\/repo"\]/,
  );
  assert.equal(result.text.includes("/nested/path.md"), false);
});

test("extracts developer instructions from the direct prompt-build payload first", () => {
  assert.deepEqual(
    extractDeveloperInstructions(
      "before_prompt_build",
      { developerInstructions: "  Direct instructions  " },
      { developerInstructions: "fallback" },
    ),
    {
      hookName: "before_prompt_build",
      developerInstructions: "Direct instructions",
    },
  );
});

test("prompt-build hook observes and replaces systemPrompt", async () => {
  const observed: string[] = [];
  const hookNames: string[] = [];
  const debug: string[] = [];
  const hook = createPromptBuildHookBehavior({
    observe(value) {
      observed.push(value.developerInstructions);
      hookNames.push(value.hookName);
    },
    debug(message) {
      debug.push(message);
    },
  });

  const result = await hook(
    {
      systemPrompt: [
        STANDARD_CORE,
        "",
        "## OpenClaw Workspace Instructions",
        "",
        "Observed",
      ].join("\n"),
    },
    {},
  );

  assert.deepEqual(
    observed,
    [[STANDARD_CORE, "", "## OpenClaw Workspace Instructions", "", "Observed"].join("\n")],
  );
  assert.deepEqual(hookNames, ["before_prompt_build"]);
  assert.deepEqual(result, {
    systemPrompt: "## OpenClaw Workspace Instructions\n\nObserved",
  });
  assert.ok(debug.some((message) => message.includes("markerIndex=")));
  assert.ok(debug.some((message) => message.includes("return=systemPrompt")));
});

test("prompt-build hook leaves non-standard envelopes unchanged", async () => {
  const observed: string[] = [];
  const debug: string[] = [];
  const hook = createPromptBuildHookBehavior({
    observe(value) {
      observed.push(value.developerInstructions);
    },
    debug(message) {
      debug.push(message);
    },
  });

  assert.equal(
    await hook(
      {
        systemPrompt: [
          "This is an OpenClaw cron automation turn.",
          "",
          "## OpenClaw Workspace Instructions",
          "",
          "## OpenClaw Agent Soul",
          "",
          "Cron-only instructions.",
        ].join("\n"),
      },
      {},
    ),
    undefined,
  );
  assert.equal(await hook({ systemPrompt: "Custom prompt without the standard envelope" }, {}), undefined);
  assert.deepEqual(observed, []);
  assert.ok(debug.some((message) => message.includes("reason=missing-standard-core")));
});

test("prompt-build hook debugs special turn marker", async () => {
  const debug: string[] = [];
  const hook = createPromptBuildHookBehavior({
    debug(message) {
      debug.push(message);
    },
  });

  assert.equal(
    await hook(
      {
        systemPrompt: [
          STANDARD_CORE,
          "",
          "## OpenClaw Workspace Instructions",
          "",
          "This is an OpenClaw heartbeat turn.",
        ].join("\n"),
      },
      {},
    ),
    undefined,
  );
  assert.ok(debug.some((message) => message.includes("reason=special-turn-marker")));
});

test("prompt-build hook debugs missing workspace marker", async () => {
  const debug: string[] = [];
  const hook = createPromptBuildHookBehavior({
    debug(message) {
      debug.push(message);
    },
  });

  assert.equal(await hook({ systemPrompt: STANDARD_CORE }, {}), undefined);
  assert.ok(debug.some((message) => message.includes("markerIndex=-1")));
  assert.ok(debug.some((message) => message.includes("reason=missing-workspace-marker")));
});

test("detects only standard OpenClaw developer instructions", () => {
  assert.equal(
    isStandardOpenClawDeveloperInstructions(
      [
        STANDARD_CORE,
        "",
        "## OpenClaw Workspace Instructions",
        "",
        "Tools",
        "",
        "## OpenClaw Agent Soul",
        "",
        "Normal turn-scoped soul instructions",
      ].join("\n"),
    ),
    true,
  );
  assert.equal(
    isStandardOpenClawDeveloperInstructions(
      [
        STANDARD_CORE,
        "",
        "## OpenClaw Workspace Instructions",
        "",
        "Tools",
        "",
        "This is an OpenClaw heartbeat turn.",
      ].join("\n"),
    ),
    false,
  );
});

test("writes generated prompt verbatim and reconciles CODEX_HOME config", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-"));
  const promptPath = resolvePromptFilePath(root, { promptFile: "generated.md" });
  const cachePath = resolveInstructionsCacheFilePath(root);
  await fs.writeFile(path.join(root, "config.toml"), 'model = "gpt-5-codex"\n');
  const source = [
    "Follow OpenClaw instructions.",
    "",
    "## OpenClaw Workspace Instructions",
    "",
    "Workspace tail.",
  ].join("\n") + "\n";

  const result = await generatePromptAndReconcileConfig({
    codexHome: root,
    promptFilePath: promptPath,
    instructionsCacheFilePath: cachePath,
    developerInstructions: source,
  });

  assert.equal(result.promptChanged, true);
  assert.equal(result.configChanged, true);
  assert.equal(result.cacheChanged, true);
  assert.equal(await fs.readFile(promptPath, "utf8"), source);
  assert.equal(await fs.readFile(cachePath, "utf8"), source);
  assert.match(await fs.readFile(path.join(root, "config.toml"), "utf8"), /model_instructions_file/);
});

test("extracts developer instructions from legacy wrapped and current raw prompts", () => {
  assert.equal(
    extractDeveloperInstructionsFromGeneratedPrompt(LEGACY_GENERATED_PROMPT),
    "Cached prompt",
  );
  assert.equal(extractDeveloperInstructionsFromGeneratedPrompt("Current raw prompt\n"), "Current raw prompt");
  assert.equal(extractDeveloperInstructionsFromGeneratedPrompt("  "), null);
});

test("resolves startup developer instructions from explicit config", async () => {
  assert.deepEqual(
    await resolveStartupDeveloperInstructions({
      config: {
        startupDeveloperInstructions: "Explicit startup",
      },
    }),
    {
      developerInstructions: "Explicit startup",
      source: "config.startupDeveloperInstructions",
    },
  );
});

test("resolves startup developer instructions from explicit file config", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-startup-"));
  const sourcePath = path.join(root, "startup.md");
  const source = [
    STANDARD_CORE,
    "",
    "## OpenClaw Workspace Instructions",
    "",
    "File workspace tail",
  ].join("\n");

  await fs.writeFile(sourcePath, source, "utf8");

  assert.deepEqual(
    await resolveStartupDeveloperInstructions({
      config: {
        startupDeveloperInstructionsFile: sourcePath,
      },
    }),
    {
      developerInstructions: source,
      source: sourcePath,
    },
  );

  assert.equal(
    renderCodexBaseInstructions(source),
    STANDARD_CORE,
  );
});

test("startup developer instructions do not fall back to cache, prompt, log, or workspace", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-startup-raw-"));
  const promptPath = resolvePromptFilePath(root, { promptFile: "generated.md" });
  const cachePath = resolveInstructionsCacheFilePath(root);
  const logPath = path.join(root, "request-system-prompts.log");

  await fs.writeFile(path.join(root, "TOOLS.md"), "Workspace tools\n", "utf8");
  await fs.writeFile(promptPath, "Raw prompt fallback\n", "utf8");
  await fs.writeFile(cachePath, "Cached startup\n", "utf8");
  await fs.writeFile(
    logPath,
    JSON.stringify({
      systemPrompt: [STANDARD_CORE, "", "## OpenClaw Workspace Instructions", "", "Logged"].join("\n"),
    }),
    "utf8",
  );

  assert.deepEqual(
    await resolveStartupDeveloperInstructions({
      config: {},
      defaultStartupDeveloperInstructionsFile: path.join(root, "missing-default.md"),
    }),
    null,
  );
});

test("resolves startup developer instructions from bundled default file", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-default-source-"));
  const sourcePath = path.join(root, "default.md");
  const source = [STANDARD_CORE, "", "## OpenClaw Workspace Instructions", "", "Default tail"].join("\n");
  await fs.writeFile(sourcePath, source, "utf8");

  assert.deepEqual(
    await resolveStartupDeveloperInstructions({
      config: {},
      defaultStartupDeveloperInstructionsFile: sourcePath,
    }),
    {
      developerInstructions: source,
      source: sourcePath,
    },
  );
});

test("resolves bundled startup developer instructions path next to compiled plugin", () => {
  assert.equal(path.basename(resolveBundledStartupDeveloperInstructionsFile()), "openclaw-developer-instructions.md");
});

test("defaults to the OpenClaw agent codex-home when CODEX_HOME is unset", () => {
  const stateRoot = path.join(os.tmpdir(), "openclaw-state-for-codex-home");

  assert.equal(
    resolveCodexHome({}, { OPENCLAW_STATE_DIR: stateRoot }),
    path.join(stateRoot, "agents", "main", "agent", "codex-home"),
  );
});

test("registers the prompt-build hook with priority options when supported", () => {
  const calls: any[] = [];
  const services: any[] = [];
  register({
    pluginConfig: {
      codexHome: "/tmp/codex-home",
    },
    registerService(service: unknown) {
      services.push(service);
    },
    on(name: string, handler: unknown, options?: unknown) {
      calls.push({ name, handler, options });
    },
    logger: {},
  });

  assert.equal(calls.length, 1);
  assert.equal(services.length, 1);
  assert.equal(services[0].id, "system-prompt");
  assert.equal(calls[0].name, "before_prompt_build");
  assert.deepEqual(calls[0].options, { priority: 10000 });
});

test("falls back to api.on without options for prompt-build hook", () => {
  const calls: any[] = [];
  const services: any[] = [];
  register({
    pluginConfig: {
      codexHome: "/tmp/codex-home",
      hookPriority: 25,
    },
    registerService(service: unknown) {
      services.push(service);
    },
    on(name: string, handler: unknown, options?: unknown) {
      if (options) {
        throw new Error("legacy api.on");
      }
      calls.push({ name, handler, options });
    },
    logger: {},
  });

  assert.equal(calls.length, 1);
  assert.equal(services.length, 1);
  assert.deepEqual(calls.map((call) => call.name), ["before_prompt_build"]);
  assert.equal(calls[0].options, undefined);
});

test("registered prompt-build handler returns workspace tail without writing base instructions", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-register-"));
  const observed: string[] = [];
  const calls: any[] = [];
  const services: any[] = [];

  register({
    pluginConfig: {
      codexHome: root,
      promptFile: "generated.md",
    },
    registerService(service: unknown) {
      services.push(service);
    },
    on(name: string, handler: unknown, options?: unknown) {
      calls.push({ name, handler, options });
    },
    logger: {
      info(message: string) {
        observed.push(message);
      },
    },
  });

  const full = [STANDARD_CORE, "", "## OpenClaw Workspace Instructions", "", "Workspace tail."].join(
    "\n",
  );
  const result = await calls[0].handler({ systemPrompt: full }, {});

  assert.equal(calls[0].name, "before_prompt_build");
  assert.deepEqual(result, {
    systemPrompt: "## OpenClaw Workspace Instructions\n\nWorkspace tail.",
  });
  await assert.rejects(fs.readFile(path.join(root, "generated.md"), "utf8"), /ENOENT/);
  await assert.rejects(
    fs.readFile(path.join(root, ".openclaw-app-server-developer-instructions.md"), "utf8"),
    /ENOENT/,
  );
  await assert.rejects(fs.readFile(path.join(root, "config.toml"), "utf8"), /ENOENT/);
  assert.equal(observed.some((message) => message.includes("observed before_prompt_build")), false);
  assert.equal(services.length, 1);
});

test("registered startup service reconciles config but does not regenerate without explicit source", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-service-"));
  const warnings: string[] = [];
  const calls: any[] = [];
  const services: any[] = [];

  await fs.writeFile(path.join(root, "TOOLS.md"), "Startup tools\n", "utf8");

  register({
    pluginConfig: {
      codexHome: root,
      promptFile: "generated.md",
      startupDeveloperInstructionsFile: path.join(root, "missing-source.md"),
    },
    registerService(service: unknown) {
      services.push(service);
    },
    on(name: string, handler: unknown, options?: unknown) {
      calls.push({ name, handler, options });
    },
    logger: {
      warn(message: string) {
        warnings.push(message);
      },
    },
  });

  await services[0].start();

  assert.equal(calls[0].name, "before_prompt_build");
  await assert.rejects(fs.readFile(path.join(root, "generated.md"), "utf8"), /ENOENT/);
  assert.match(await fs.readFile(path.join(root, "config.toml"), "utf8"), /model_instructions_file/);
  assert.ok(warnings.some((message) => message.includes("no canonical developer instructions source")));
});

test("registered startup service writes prompt from explicit startup source", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "system-prompt-service-explicit-"));
  const observed: string[] = [];
  const calls: any[] = [];
  const services: any[] = [];

  register({
    pluginConfig: {
      codexHome: root,
      promptFile: "generated.md",
      startupDeveloperInstructions: [
        STANDARD_CORE,
        "",
        "## OpenClaw Workspace Instructions",
        "",
        "Workspace tail.",
      ].join("\n"),
    },
    registerService(service: unknown) {
      services.push(service);
    },
    on(name: string, handler: unknown, options?: unknown) {
      calls.push({ name, handler, options });
    },
    logger: {
      info(message: string) {
        observed.push(message);
      },
    },
  });

  await services[0].start();

  assert.equal(calls[0].name, "before_prompt_build");
  assert.equal(
    await fs.readFile(path.join(root, "generated.md"), "utf8"),
    [STANDARD_CORE, "", "## OpenClaw Workspace Instructions", "", "Workspace tail."].join("\n"),
  );
  assert.match(await fs.readFile(path.join(root, "config.toml"), "utf8"), /model_instructions_file/);
  assert.ok(observed.some((message) => message.includes("startup generated prompt")));
});
